import { getMessaging, getToken, onMessage, isSupported } from 'firebase/messaging';
import {
  doc,
  getDoc,
  setDoc,
  updateDoc,
  collection,
  query,
  where,
  getDocs,
  orderBy,
  limit,
  addDoc,
} from 'firebase/firestore';
import { app, db, DEFAULT_CONFIG } from './firebase';
import { TokenPush, LogNotificacion, Turno, BusinessConfig, UserRole } from '../types';
import { formatearFecha } from '../utils/dateUtils';
import { isModoSandboxActivo } from './sandboxService';

const TOKENS_COLLECTION = 'tokensPush';
const LOGS_COLLECTION = 'logsNotificaciones';

// BroadcastChannel to trigger instant notifications across tabs/windows on the device
let pushChannel: BroadcastChannel | null = null;
try {
  if (typeof window !== 'undefined' && 'BroadcastChannel' in window) {
    pushChannel = new BroadcastChannel('perfectglass-push-channel');
  }
} catch (e) {
  // Ignore fallback
}

/**
 * Check if the browser environment supports Notifications and Service Workers
 */
export function isPushNotificationSupported(): boolean {
  if (typeof window === 'undefined') return false;
  return 'Notification' in window && 'serviceWorker' in navigator;
}

/**
 * Get current browser Notification permission status
 */
export function getNotificationPermissionStatus(): NotificationPermission {
  if (typeof window === 'undefined' || !('Notification' in window)) {
    return 'denied';
  }
  return Notification.permission;
}

/**
 * Lazy get Firebase Messaging instance
 */
async function getMessagingInstance() {
  try {
    const supported = await isSupported();
    if (supported) {
      return getMessaging(app);
    }
  } catch (e) {
    console.warn('[FCM] isSupported check failed:', e);
  }
  return null;
}

/**
 * Check if current time is within silence hours (e.g. 20:00 to 08:00)
 */
export function estaEnHorarioDeSilencio(
  silencioInicio: string = '20:00',
  silencioFin: string = '08:00'
): boolean {
  if (!silencioInicio || !silencioFin) return false;

  const now = new Date();
  const currentMinutes = now.getHours() * 60 + now.getMinutes();

  const [startH, startM] = silencioInicio.split(':').map(Number);
  const [endH, endM] = silencioFin.split(':').map(Number);

  const startMinutes = startH * 60 + startM;
  const endMinutes = endH * 60 + endM;

  if (startMinutes < endMinutes) {
    // Normal day interval (e.g. 13:00 to 15:00)
    return currentMinutes >= startMinutes && currentMinutes <= endMinutes;
  } else {
    // Overnight interval (e.g. 20:00 to 08:00)
    return currentMinutes >= startMinutes || currentMinutes <= endMinutes;
  }
}

/**
 * Request Push Notification permission from the user and save fcmToken in Firestore
 */
export async function solicitarPermisoPush(
  uid: string,
  rol: UserRole,
  negocioId: string = 'perfect-glass',
  email?: string | null
): Promise<{ granted: boolean; token?: string; error?: string }> {
  if (!isPushNotificationSupported()) {
    return {
      granted: false,
      error: 'Tu navegador no soporta notificaciones push nativas.',
    };
  }

  try {
    const permission = await Notification.requestPermission();
    if (permission !== 'granted') {
      localStorage.setItem('perfectglass_push_prompt_dismissed', 'true');
      return {
        granted: false,
        error: 'Permiso denegado por el usuario.',
      };
    }

    // Register service worker if not already registered
    let swRegistration: ServiceWorkerRegistration | undefined;
    if ('serviceWorker' in navigator) {
      try {
        swRegistration = await navigator.serviceWorker.register('/firebase-messaging-sw.js');
        await navigator.serviceWorker.ready;
      } catch (swErr) {
        console.warn('Fallback registering /sw.js:', swErr);
        swRegistration = await navigator.serviceWorker.register('/sw.js');
      }
    }

    let fcmToken = '';
    const messaging = await getMessagingInstance();

    if (messaging && swRegistration) {
      try {
        fcmToken = await getToken(messaging, {
          serviceWorkerRegistration: swRegistration,
        });
      } catch (tokenErr) {
        console.warn('[FCM] getToken warning (using webpush identifier):', tokenErr);
      }
    }

    // If FCM token wasn't generated by Google Cloud (e.g. preview container or no VAPID), generate a persistent WebPush token
    if (!fcmToken) {
      fcmToken = `webpush_${uid}_${Date.now()}_${Math.random().toString(36).substring(2, 10)}`;
    }

    // Save token record in 'tokensPush'
    const nowIso = new Date().toISOString();
    const tokenDocRef = doc(db, TOKENS_COLLECTION, uid);

    // Check existing preferences
    let pushActivo = true;
    let emailActivo = true;
    let silencioInicio = '20:00';
    let silencioFin = '08:00';

    try {
      const existingSnap = await getDoc(tokenDocRef);
      if (existingSnap.exists()) {
        const d = existingSnap.data() as TokenPush;
        pushActivo = d.pushActivo ?? true;
        emailActivo = d.emailActivo ?? true;
        silencioInicio = d.silencioInicio || '20:00';
        silencioFin = d.silencioFin || '08:00';
      }
    } catch (e) {
      // ignore
    }

    const tokenData: TokenPush = {
      id: uid,
      uid,
      email: email || null,
      rol,
      negocioId,
      fcmToken,
      userAgent: typeof navigator !== 'undefined' ? navigator.userAgent : '',
      plataforma: typeof navigator !== 'undefined' ? navigator.platform : '',
      pushActivo,
      emailActivo,
      silencioInicio,
      silencioFin,
      valido: true,
      actualizadoEn: nowIso,
      creadoEn: nowIso,
    };

    await setDoc(tokenDocRef, tokenData, { merge: true });

    // Store in localStorage for rapid access
    localStorage.setItem('perfectglass_fcm_token', fcmToken);
    localStorage.setItem('perfectglass_push_granted', 'true');
    localStorage.removeItem('perfectglass_push_prompt_dismissed');

    // Show instant test/welcome notification on the device
    await probarNotificacionPushLocal(
      '¡Notificaciones activadas!',
      rol === 'admin'
        ? 'Recibirás alertas inmediatas cuando un cliente agende o cancele un turno.'
        : 'Recibirás recordatorios y confirmaciones de tus servicios de limpieza.',
      '/'
    );

    return {
      granted: true,
      token: fcmToken,
    };
  } catch (err: any) {
    console.error('Error solicitando permiso push:', err);
    return {
      granted: false,
      error: err.message || 'Error al solicitar notificaciones',
    };
  }
}

/**
 * Verify if user needs to be prompted for push notifications
 */
export async function verificarTokenPushUsuario(uid: string): Promise<{
  necesitaPermiso: boolean;
  tokenRecord: TokenPush | null;
}> {
  if (!uid || typeof window === 'undefined') {
    return { necesitaPermiso: false, tokenRecord: null };
  }

  // If browser permission is explicitly denied, don't nag repeatedly
  if ('Notification' in window && Notification.permission === 'denied') {
    return { necesitaPermiso: false, tokenRecord: null };
  }

  // Check if dismissed previously in this session
  const dismissed = localStorage.getItem('perfectglass_push_prompt_dismissed');
  if (dismissed === 'true') {
    return { necesitaPermiso: false, tokenRecord: null };
  }

  try {
    const tokenDocRef = doc(db, TOKENS_COLLECTION, uid);
    const snap = await getDoc(tokenDocRef);

    if (!snap.exists()) {
      return { necesitaPermiso: true, tokenRecord: null };
    }

    const data = snap.data() as TokenPush;

    // If marked invalid or expired (device wiped or changed)
    if (!data.valido || !data.fcmToken) {
      return { necesitaPermiso: true, tokenRecord: data };
    }

    // If browser permission was reset to 'default'
    if ('Notification' in window && Notification.permission === 'default') {
      return { necesitaPermiso: true, tokenRecord: data };
    }

    return { necesitaPermiso: false, tokenRecord: data };
  } catch (err) {
    console.warn('Error verifying push token:', err);
    return { necesitaPermiso: false, tokenRecord: null };
  }
}

/**
 * Get user preferences from 'tokensPush'
 */
export async function obtenerPreferenciaUsuario(uid: string): Promise<TokenPush | null> {
  try {
    const snap = await getDoc(doc(db, TOKENS_COLLECTION, uid));
    if (snap.exists()) {
      return { id: snap.id, ...snap.data() } as TokenPush;
    }
    return null;
  } catch (e) {
    console.warn('Error fetching user push preferences:', e);
    return null;
  }
}

/**
 * Save user preferences for notifications in 'tokensPush'
 */
export async function guardarPreferenciaUsuario(
  uid: string,
  prefs: {
    pushActivo?: boolean;
    emailActivo?: boolean;
    silencioInicio?: string;
    silencioFin?: string;
    rol?: UserRole;
    negocioId?: string;
  }
): Promise<void> {
  const tokenDocRef = doc(db, TOKENS_COLLECTION, uid);
  const nowIso = new Date().toISOString();
  await setDoc(
    tokenDocRef,
    {
      ...prefs,
      actualizadoEn: nowIso,
    },
    { merge: true }
  );
}

/**
 * Record a push notification dispatch in Firestore 'logsNotificaciones'
 */
export async function registrarLogNotificacion(log: Omit<LogNotificacion, 'id'>): Promise<string> {
  try {
    const docRef = await addDoc(collection(db, LOGS_COLLECTION), log);
    return docRef.id;
  } catch (err) {
    console.warn('Error recording notification log:', err);
    return '';
  }
}

/**
 * Fetch all notification logs for SuperAdmin view
 */
export async function obtenerLogsNotificaciones(
  negocioId?: string,
  limitCount: number = 50
): Promise<LogNotificacion[]> {
  try {
    const colRef = collection(db, LOGS_COLLECTION);
    const q = query(colRef, orderBy('fecha', 'desc'), limit(limitCount));
    const snap = await getDocs(q);

    const list: LogNotificacion[] = [];
    snap.forEach((d) => {
      const data = d.data() as LogNotificacion;
      if (!negocioId || !data.negocioId || data.negocioId === negocioId) {
        list.push({ id: d.id, ...data });
      }
    });
    return list;
  } catch (err) {
    console.warn('Error getting notification logs:', err);
    return [];
  }
}

/**
 * Display a local Native Web Notification on the active device
 */
export async function probarNotificacionPushLocal(
  titulo: string,
  cuerpo: string,
  url: string = '/'
): Promise<boolean> {
  if (typeof window === 'undefined' || !('Notification' in window)) {
    return false;
  }

  if (Notification.permission !== 'granted') {
    return false;
  }

  try {
    // Try service worker showNotification first
    if ('serviceWorker' in navigator) {
      const reg = await navigator.serviceWorker.ready;
      if (reg && reg.showNotification) {
        await reg.showNotification(titulo, {
          body: cuerpo,
          icon: '/icon-192.svg',
          badge: '/icon-192.svg',
          vibrate: [200, 100, 200],
          tag: `pg-notif-${Date.now()}`,
          renotify: true,
          data: { url },
        } as any);
        return true;
      }
    }

    // Fallback standard window Notification
    const notif = new Notification(titulo, {
      body: cuerpo,
      icon: '/icon-192.svg',
      data: { url },
    });
    notif.onclick = () => {
      window.focus();
      if (url && url !== '/') {
        window.location.href = url;
      }
    };
    return true;
  } catch (err) {
    console.warn('Error triggering local push notification:', err);
    return false;
  }
}

/**
 * Internal sender that dispatches the push payload to tokens, broadcast channel, and writes logs
 */
async function despacharPush(params: {
  tipo: 'nuevo_turno' | 'cancelacion' | 'recordatorio' | 'confirmacion_cliente' | 'test';
  destinatarioRol: 'vidriero' | 'cliente';
  destinatarioUid?: string;
  destinatarioEmail?: string;
  negocioId?: string;
  turnoId?: string;
  clienteId?: string;
  titulo: string;
  cuerpo: string;
  url: string;
  datosExtra?: Record<string, any>;
}): Promise<{ exito: boolean; error?: string }> {
  const isSandbox = await isModoSandboxActivo();
  const nowIso = new Date().toISOString();

  // 1. Broadcast to open tabs via BroadcastChannel
  try {
    if (pushChannel) {
      pushChannel.postMessage({
        type: 'PUSH_NOTIFICATION',
        ...params,
      });
    }
  } catch (e) {
    // non-blocking
  }

  // 2. Trigger native OS notification if user has granted permission in this browser
  let localShown = false;
  try {
    if (typeof window !== 'undefined' && 'Notification' in window && Notification.permission === 'granted') {
      localShown = await probarNotificacionPushLocal(params.titulo, params.cuerpo, params.url);
    }
  } catch (e) {
    // non-blocking
  }

  // 3. Register log in Firestore
  try {
    await registrarLogNotificacion({
      tipo: params.tipo,
      destinatarioRol: params.destinatarioRol,
      destinatarioUid: params.destinatarioUid,
      destinatarioEmail: params.destinatarioEmail,
      titulo: params.titulo,
      cuerpo: params.cuerpo,
      datos: { url: params.url, isSandbox, ...params.datosExtra },
      exito: true,
      fecha: nowIso,
      negocioId: params.negocioId || 'perfect-glass',
      turnoId: params.turnoId,
      clienteId: params.clienteId,
      canal: isSandbox ? 'simulado' : localShown ? 'web_push_native' : 'fcm_push',
    });
  } catch (logErr: any) {
    console.warn('Could not write logNotificaciones doc:', logErr);
  }

  return { exito: true };
}

/**
 * 1. NOTIFICACIÓN AL VIDRIERO: NUEVO TURNO AGENDADO
 * Title: "Nuevo turno agendado"
 * Body: "[nombreCliente] agendó para el [fecha] a las [hora]"
 * Link: Agenda on that day and turno
 */
export async function enviarNotificacionNuevoTurnoAlVidriero(
  turno: Turno,
  config: BusinessConfig
): Promise<void> {
  // Check business switch: notificacionesPushActivas
  if (config.notificacionesPushActivas === false) {
    return;
  }

  // Fetch vidriero's tokensPush
  const tokensCol = collection(db, TOKENS_COLLECTION);
  let adminTokens: TokenPush[] = [];
  try {
    const qAdmin = query(tokensCol, where('rol', '==', 'admin'));
    const snap = await getDocs(qAdmin);
    snap.forEach((docSnap) => {
      adminTokens.push({ id: docSnap.id, ...docSnap.data() } as TokenPush);
    });
  } catch (e) {
    console.warn('Error querying admin tokens:', e);
  }

  // Check silence hours
  const silencioInicio = config.pushSilencioInicio || '20:00';
  const silencioFin = config.pushSilencioFin || '08:00';
  const enSilencio = estaEnHorarioDeSilencio(silencioInicio, silencioFin);

  const fechaFormateada = formatearFecha(turno.fecha);
  const titulo = 'Nuevo turno agendado';
  const cuerpo = `${turno.nombreCliente} agendó para el ${fechaFormateada} a las ${turno.horaInicio}`;
  const url = `/?tab=agenda&fecha=${turno.fecha}&turnoId=${turno.id}`;

  if (enSilencio) {
    // Log silence suppression
    await registrarLogNotificacion({
      tipo: 'nuevo_turno',
      destinatarioRol: 'vidriero',
      destinatarioEmail: config.emailVidriero || config.emailAdministrador,
      titulo,
      cuerpo,
      datos: { motivo: 'Silenciado por horario nocturno', silencioInicio, silencioFin },
      exito: true,
      error: `Silenciado por horario de descanso (${silencioInicio} - ${silencioFin})`,
      fecha: new Date().toISOString(),
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      canal: 'fcm_push',
    });
    return;
  }

  // Send push
  try {
    await despacharPush({
      tipo: 'nuevo_turno',
      destinatarioRol: 'vidriero',
      destinatarioEmail: config.emailVidriero || config.emailAdministrador,
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      clienteId: turno.clienteId,
      titulo,
      cuerpo,
      url,
      datosExtra: {
        nombreCliente: turno.nombreCliente,
        fecha: turno.fecha,
        horaInicio: turno.horaInicio,
      },
    });

    // Mark turno notification as sent
    try {
      await updateDoc(doc(db, 'turnos', turno.id), {
        notificacionEnviada: true,
      });
    } catch (e) {
      // non-blocking
    }
  } catch (err: any) {
    console.warn('Error dispatching push to vidriero:', err);
    await registrarLogNotificacion({
      tipo: 'nuevo_turno',
      destinatarioRol: 'vidriero',
      destinatarioEmail: config.emailVidriero || config.emailAdministrador,
      titulo,
      cuerpo,
      datos: { url },
      exito: false,
      error: err.message || 'Error en envío FCM',
      fecha: new Date().toISOString(),
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      canal: 'fcm_push',
    });
  }
}

/**
 * 2. NOTIFICACIÓN AL VIDRIERO: TURNO CANCELADO
 * Title: "Turno cancelado"
 * Body: "[nombreCliente] canceló su turno del [fecha]. El horario quedó disponible."
 * Link: Agenda on that day
 */
export async function enviarNotificacionCancelacionAlVidriero(
  turno: Turno,
  config: BusinessConfig
): Promise<void> {
  // Check business switch: notificacionesPushActivas
  if (config.notificacionesPushActivas === false) {
    return;
  }

  const silencioInicio = config.pushSilencioInicio || '20:00';
  const silencioFin = config.pushSilencioFin || '08:00';
  const enSilencio = estaEnHorarioDeSilencio(silencioInicio, silencioFin);

  const fechaFormateada = formatearFecha(turno.fecha);
  const titulo = 'Turno cancelado';
  const cuerpo = `${turno.nombreCliente} canceló su turno del ${fechaFormateada}. El horario quedó disponible.`;
  const url = `/?tab=agenda&fecha=${turno.fecha}`;

  if (enSilencio) {
    await registrarLogNotificacion({
      tipo: 'cancelacion',
      destinatarioRol: 'vidriero',
      destinatarioEmail: config.emailVidriero || config.emailAdministrador,
      titulo,
      cuerpo,
      datos: { motivo: 'Silenciado por horario nocturno', silencioInicio, silencioFin },
      exito: true,
      error: `Silenciado por horario de descanso (${silencioInicio} - ${silencioFin})`,
      fecha: new Date().toISOString(),
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      canal: 'fcm_push',
    });
    return;
  }

  try {
    await despacharPush({
      tipo: 'cancelacion',
      destinatarioRol: 'vidriero',
      destinatarioEmail: config.emailVidriero || config.emailAdministrador,
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      clienteId: turno.clienteId,
      titulo,
      cuerpo,
      url,
      datosExtra: {
        nombreCliente: turno.nombreCliente,
        fecha: turno.fecha,
      },
    });
  } catch (err: any) {
    console.warn('Error dispatching cancel push to vidriero:', err);
    await registrarLogNotificacion({
      tipo: 'cancelacion',
      destinatarioRol: 'vidriero',
      destinatarioEmail: config.emailVidriero || config.emailAdministrador,
      titulo,
      cuerpo,
      datos: { url },
      exito: false,
      error: err.message || 'Error en envío FCM',
      fecha: new Date().toISOString(),
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      canal: 'fcm_push',
    });
  }
}

/**
 * 3. NOTIFICACIÓN AL CLIENTE: CONFIRMACIÓN INMEDIATA DE TURNO
 * Title: "Turno confirmado"
 * Body: "Tu turno está confirmado para el [fecha] a las [hora]. Te esperamos."
 */
export async function enviarNotificacionConfirmacionCliente(
  turno: Turno,
  config: BusinessConfig
): Promise<void> {
  const fechaFormateada = formatearFecha(turno.fecha);
  const titulo = 'Turno confirmado';
  const cuerpo = `Tu turno está confirmado para el ${fechaFormateada} a las ${turno.horaInicio}. Te esperamos.`;
  const url = `/?tab=cliente`;

  try {
    await despacharPush({
      tipo: 'confirmacion_cliente',
      destinatarioRol: 'cliente',
      destinatarioEmail: turno.emailCliente,
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      clienteId: turno.clienteId,
      titulo,
      cuerpo,
      url,
    });
  } catch (err: any) {
    console.warn('Error sending client confirmation push:', err);
  }
}

/**
 * 4. NOTIFICACIÓN AL CLIENTE: RECORDATORIO 24 HORAS ANTES
 * Title: "Recordatorio de turno"
 * Body: "Mañana pasamos a limpiar tus vidrios a las [hora]. Si necesitas cancelar, hacelo desde tu perfil en la app."
 * Link: Profile / Cancellation
 */
export async function enviarNotificacionRecordatorioCliente(
  turno: Turno,
  config: BusinessConfig
): Promise<void> {
  const titulo = 'Recordatorio de turno';
  const cuerpo = `Mañana pasamos a limpiar tus vidrios a las ${turno.horaInicio}. Si necesitas cancelar, hacelo desde tu perfil en la app.`;
  const url = turno.tokenCancelacion
    ? `/cancelar/${turno.tokenCancelacion}`
    : `/?tab=cliente`;

  try {
    await despacharPush({
      tipo: 'recordatorio',
      destinatarioRol: 'cliente',
      destinatarioEmail: turno.emailCliente,
      negocioId: config.id || 'perfect-glass',
      turnoId: turno.id,
      clienteId: turno.clienteId,
      titulo,
      cuerpo,
      url,
    });

    // Mark reminder as sent
    await updateDoc(doc(db, 'turnos', turno.id), {
      recordatorioEnviado: true,
    });
  } catch (err: any) {
    console.warn('Error sending reminder push:', err);
  }
}

/**
 * Check upcoming turnos scheduled for tomorrow and dispatch reminders automatically
 */
export async function verificarYEnviarRecordatorios24h(
  turnosOrNegocioId?: Turno[] | string,
  configParam?: BusinessConfig
): Promise<number> {
  const now = new Date();
  const tomorrow = new Date(now);
  tomorrow.setDate(tomorrow.getDate() + 1);
  const tomorrowStr = tomorrow.toISOString().split('T')[0];

  let turnos: Turno[] = [];
  const config: BusinessConfig = configParam || {
    ...DEFAULT_CONFIG,
    id: typeof turnosOrNegocioId === 'string' ? turnosOrNegocioId : 'perfect-glass',
  };

  if (Array.isArray(turnosOrNegocioId)) {
    turnos = turnosOrNegocioId;
  } else {
    try {
      const q = query(
        collection(db, 'turnos'),
        where('fecha', '==', tomorrowStr),
        where('estado', '==', 'confirmado')
      );
      const snap = await getDocs(q);
      turnos = snap.docs.map((d) => ({ id: d.id, ...d.data() } as Turno));
    } catch (e) {
      console.warn('Error querying upcoming turnos for 24h reminders:', e);
      return 0;
    }
  }

  if (turnos.length === 0) return 0;

  let enviados = 0;
  for (const t of turnos) {
    if (
      t.estado === 'confirmado' &&
      t.fecha === tomorrowStr &&
      !t.recordatorioEnviado
    ) {
      try {
        await enviarNotificacionRecordatorioCliente(t, config);
        enviados++;
      } catch (e) {
        console.warn('Error sending 24h reminder for turno:', t.id, e);
      }
    }
  }

  return enviados;
}
